<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="8" hostname="DESKTOP-EROT39V" failures="2" tests="10" name="Test" time="3.53" errors="0" timestamp="2025-05-23T20:24:26 IST">
  <testcase classname="apis.CreateUserTest" name="createUserNegative" time="1.384"/>
  <testcase classname="apis.CreateUserTest" name="createUserPositive" time="1.384"/>
  <testcase classname="apis.DeleteUserTest" name="deleteUserNegative" time="1.384"/>
  <testcase classname="apis.GetUserByNameTest" name="getUserPositive" time="1.393">
    <skipped/>
  </testcase> <!-- getUserPositive -->
  <testcase classname="apis.GetUserByNameTest" name="getUserNegative" time="1.384"/>
  <testcase classname="apis.GetUserByNameTest" name="getUserPositive" time="1.015">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at apis.GetUserByNameTest.getUserPositive(GetUserByNameTest.java:24)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- getUserPositive -->
  <testcase classname="apis.DeleteUserTest" name="deleteUserPositive" time="1.034">
    <skipped/>
  </testcase> <!-- deleteUserPositive -->
  <testcase classname="apis.UpdateUserTest" name="updateUserPositive" time="1.031"/>
  <testcase classname="apis.UpdateUserTest" name="updateUserNegative" time="1.05"/>
  <testcase classname="apis.DeleteUserTest" name="deleteUserPositive" time="1.07">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at apis.DeleteUserTest.deleteUserPositive(DeleteUserTest.java:28)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- deleteUserPositive -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
  <testcase classname="base.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="base.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
  <testcase classname="base.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="base.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
</testsuite> <!-- Test -->
